site_name: Документация проекта
theme:
  name: material

nav:
  - Введение: index.md
  - Руководство: guide.md
  - Видеоуроки: video.md
  - ПЛС ЧЕРНОМОРСК: ilk_001_main.md

extra_javascript:
  - pagefind/pagefind-ui.js
extra_css:
  - pagefind/pagefind-ui.css
