site_name: Документация ИС «ЕМЛС Дунай» • «ПЛС Черноморск»
theme:
  name: material
  language: ru
  custom_dir: overrides
  features:
    - navigation.sections     # многоуровневое меню
    - navigation.expand       # раскрывать подразделы
    - navigation.top          # кнопка "вверх"
    - header.autohide         # шапка прилипала
    - toc.integrate           # оглавление в боковой панели    
    - content.code.copy       # копирование кода кнопкой
    - content.tabs.link       # вкладки
    - content.tooltips        # всплывающие подсказки    
markdown_extensions:
  - toc
  - admonition
  - pymdownx.details          # раскрывающиеся блоки (??? note)
  - pymdownx.superfences:      # вкладки (=== "Python")
    custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true   # красивый стиль вкладок
  - attr_list                 # классы для кнопок и стилей
  - def_list                  # поддержка списков-определений
  - footnotes                 # сноски
  - md_in_html                # HTML внутри markdown
  - toc:
      permalink: true         # якорные ссылки в заголовках
  - pymdownx.highlight:
      anchor_linenums: true  
  - codehilite
  - pymdownx.superfences
  - attr_list    
  - pymdownx.inlinehilite     # плагин Python
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark             # ==выделение==
  - pymdownx.critic           # дополнения/удаления текста
  - pymdownx.caret            # ^надстрочный текст^
  - pymdownx.tilde            # ~подстрочный текст~
  - pymdownx.smartsymbols     # спец. символы  
nav:
  - Введение: index.md
  - Регистрация: register.md
  - Ввод заявок: logreq.md
  - Ввод заявок Диспетчером: logreq_disp.md
  - Статотчеты: report_01_zagal.md
  - Ошибки в СПР судов: instr_video_05_sprships_01.md
  - Парсинг регистров: instr_video_06_sprships_equasis_03.md
  - РІВНІ ДУНАЮ ► ЧАТ - БОТ: instr_video_07_bonilevels.md
  - ПЛС ЧЕРНОМОРСК: ilk_001_main.md
  - CheatSheet: cheatsheet.md   # 🔥 добавляем мой справочник

palette:
    primary: blue
    accent: indigo
extra_javascript:
  - pagefind/pagefind-ui.js
extra_css:
  - pagefind/pagefind-ui.css
  - styles.css
plugins:
  - search: false   # отключаем стандартный поиск MkDocs
