site_name: Документация ИС ЕМЛС «Дунай»
theme:
  name: material
  custom_dir: overrides

nav:
  - Введение: index.md
  - Руководство: guide.md
  - Видеоуроки: video.md
  - ПЛС ЧЕРНОМОРСК: ilk_001_main.md

extra_javascript:
  - pagefind/pagefind-ui.js
extra_css:
  - pagefind/pagefind-ui.css
