site_name: Документация ИС «ЕМЛС Дунай» • «ПЛС Черноморск»
theme:
  name: material
  language: ru
  custom_dir: overrides
  palette:
    - scheme: default
      primary: blue
      accent: indigo
  features:
    #- navigation.sections     # многоуровневое меню
    - navigation.expand       # раскрывать подразделы
    - navigation.top          # кнопка "вверх"
    - header.autohide         # шапка прилипала
    - toc.integrate           # оглавление в боковой панели    
    - content.code.copy       # копирование кода кнопкой
    - content.tabs.link       # вкладки
    - content.tooltips        # всплывающие подсказки    
    #- navigation.tabs         # вкладки в меню
markdown_extensions:
  - toc
  - admonition
  - pymdownx.details          # раскрывающиеся блоки (??? note)
  - pymdownx.superfences:      # вкладки (=== "Python")
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true   # красивый стиль вкладок
  - attr_list                 # классы для кнопок и стилей
  - def_list                  # поддержка списков-определений
  - footnotes                 # сноски
  - md_in_html                # HTML внутри markdown
  - toc:
      permalink: true         # якорные ссылки в заголовках
  - pymdownx.highlight:
      anchor_linenums: true  
  - codehilite
  - attr_list    
  - pymdownx.inlinehilite     # плагин Python
  - pymdownx.snippets
  - pymdownx.keys
  - pymdownx.mark             # ==выделение==
  - pymdownx.critic           # дополнения/удаления текста
  - pymdownx.caret            # ^надстрочный текст^
  - pymdownx.tilde            # ~подстрочный текст~
  - pymdownx.smartsymbols     # спец. символы  
nav:
  - Как это работает: how_it_works.md
  - Введение: index.md
  - Регистрация: register.md
  - Ввод заявок: logreq.md
  - Ввод заявок Диспетчером: logreq_disp.md
  - 📊 Статотчеты : 
      - Дунай: reports/report_01_zagal.md
      - Проведення лоцмана за місяць: reports/report_02_pilot_one_month.md
      - Кількість робіт: reports/report_03_prov_pilot_month.md
      - График отпусков (Дунай): reports/report_04_grafik_otpuskov2026.md
      - 📅 Графіки змін (Дунай): reports/report_05_grafik_smen.md
  - Ошибки в СПР судов: instr_video_05_sprships_01.md
  - Парсинг регистров: instr_video_06_sprships_equasis_03.md
  - РІВНІ ДУНАЮ ► ЧАТ - БОТ: instr_video_07_bonilevels.md
  - Проводки ЛС: 
      - Реестр: reestr.md
      - ↕️ Сортировка и фильтры: reestr_001_filter_sort.md
      - ⚠️ Замечания: ilk_prov_err_001_photo.md
      - 📸 Скан кв-ии: instr_video_08_scan_photo.md
      - ✂️ Пакетная обрезка фото квитанций: instr_video_09_packet_photo_crop.md
  - ПЛС ЧЕРНОМОРСК: ilk_001_main.md
  - РОЗПОДІЛ ЛОЦМАНІВ: instr_video_10_rozpodil.md
#  - CheatSheet: cheatsheet.md   # 🔥 добавляем мой справочник

palette:
    primary: blue
    accent: indigo
extra_javascript:
  - pagefind/pagefind-ui.js
  - https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js
extra_css:
  - pagefind/pagefind-ui.css
  - styles.css
  - https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css
plugins:
  - search: false   # отключаем стандартный поиск MkDocs