name: Deploy Documentation

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install MkDocs + theme + Pagefind CLI
        run: |
          pip install --upgrade pip
          pip install mkdocs mkdocs-material "pagefind[bin]"
          python -m pagefind --version

      - name: Build MkDocs site
        run: mkdocs build --clean

      - name: Generate Pagefind index
        run: python -m pagefind --site ./site --output-subdir pagefind

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
