name: Deploy Documentation

on:
  push:
    branches: [ main ]  # Собираем при пуше в main

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Клонируем репозиторий
      - uses: actions/checkout@v4

      # 2. Устанавливаем Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      # 3. Устанавливаем MkDocs, Material и Pagefind CLI
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mkdocs mkdocs-material "pagefind[bin]"

      # 4. Строим сайт MkDocs
      - name: Build MkDocs site
        run: mkdocs build --clean

      # 5. Индексируем контент Pagefind
      - name: Generate Pagefind index
        run: python -m pagefind --site ./site

      # 6. Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
